# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Raito Bezarius' adventures
tagline:             'A heroic fantasy story (wtf) about someone who just wanted to write code'
description:         'A blog where I talk about code, animes and what I think about thing around me (thanks to <a href="https://twitter.com/mdo" target="_blank">@mdo</a> for this cool theme!)'
url:                 http://www.raitobezarius.me/
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Raito Bezarius
  url:               https://twitter.com/Ra1t0_Bezar1us
  email:             masterancpp@gmail.com

# Custom vars
version:             1.0.0
